kind: pipeline
name: default

# steps:
#- name: build 
#  image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
#  commands:
#  - dotnet publish "todoapi.csproj" -c Release -o ./publish --runtime alpine-x64 --self-contained true /p:PublishTrimmed=true /p:TrimMode=Link /p:PublishSingleFile=true

steps:
- name: publish-local-registry 
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags: latest
    insecure: true
    registry: "registry.gujarulabs.cc"
    repo: "gujarulabs.cc/todoapi"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password