kind: pipeline
name: default

steps:
  - name: build 
    image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    commands:
      - dotnet publish "todoapi.csproj" -c Release -o ./publish --runtime alpine-x64 --self-contained true /p:PublishTrimmed=true /p:TrimMode=Link /p:PublishSingleFile=true

  - name: publish-local-registry 
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      tags: latest
      insecure: false 
      registry: registry.gujarulab.cc
      repo: registry.gujarulab.cc/todoapi
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password